//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FenergoEntities : DbContext
    {
        public FenergoEntities()
            : base("name=FenergoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LEBranchSDSCounterparty> LEBranchSDSCounterparties { get; set; }
        public virtual DbSet<LegalEntityExtension> LegalEntityExtensions { get; set; }
        public virtual DbSet<LESDSCounterparty> LESDSCounterparties { get; set; }
        public virtual DbSet<LESubAccountSDSCounterparty> LESubAccountSDSCounterparties { get; set; }
        public virtual DbSet<LETMSAccount> LETMSAccounts { get; set; }
        public virtual DbSet<LegalEntity> LegalEntities { get; set; }
    }
}
