//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomingMessage
    {
        public System.Guid IncomingMessageId { get; set; }
        public byte MessageStatusId { get; set; }
        public short MessageQueueId { get; set; }
        public string Format { get; set; }
        public string XmlMessage { get; set; }
        public string ErrorMessage { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ProcessedOn { get; set; }
        public Nullable<int> MessageProcessingDurationInSec { get; set; }
    }
}
