//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LegalEntity()
        {
            this.LegalEntityExtensions = new HashSet<LegalEntityExtension>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] RowVersion { get; set; }
        public short LegalEntitySubtypeId { get; set; }
        public Nullable<short> LegalEntityCategoryId { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<short> LegalEntityRoleStatusId { get; set; }
        public Nullable<bool> IsMigrated { get; set; }
        public string ReferenceId { get; set; }
        public Nullable<bool> Private { get; set; }
        public Nullable<short> LookupLegalEntityEditStatusId { get; set; }
        public Nullable<short> LookupLegalEntityReasonForChangeId { get; set; }
        public string OtherReasonNotes { get; set; }
        public string EditingUser { get; set; }
        public Nullable<System.DateTime> LastVerifiedDate { get; set; }
        public Nullable<int> MasterCaseId { get; set; }
        public string EditNotes { get; set; }
        public Nullable<System.DateTime> CreditReviewDate { get; set; }
        public Nullable<System.DateTime> NextReviewDate { get; set; }
        public Nullable<short> LookupLegalEntityStatusId { get; set; }
        public Nullable<short> PaymentTypeId { get; set; }
        public Nullable<System.DateTime> AnnualReturnDate { get; set; }
        public string LegalJurisdiction { get; set; }
        public Nullable<System.DateTime> FscsReviewDate { get; set; }
        public Nullable<short> GroupEntityId { get; set; }
        public Nullable<bool> IsCustomer { get; set; }
        public Nullable<short> NationalCountryId { get; set; }
    
        public virtual LEBranchSDSCounterparty LEBranchSDSCounterparty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegalEntityExtension> LegalEntityExtensions { get; set; }
        public virtual LESDSCounterparty LESDSCounterparty { get; set; }
        public virtual LESubAccountSDSCounterparty LESubAccountSDSCounterparty { get; set; }
        public virtual LETMSAccount LETMSAccount { get; set; }
    }
}
