//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LETMSAccount
    {
        public int LegalEntityId { get; set; }
        public Nullable<long> SdsId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string LongName { get; set; }
        public string ShortName { get; set; }
        public Nullable<short> OwnerQuantity { get; set; }
        public Nullable<short> NumberOfProfiles { get; set; }
        public string ResidenceCountryCode { get; set; }
        public string LegalCountryCode { get; set; }
        public string MasterNumber { get; set; }
        public string AccountCategoryType { get; set; }
        public Nullable<int> CpiSsiCount { get; set; }
        public string SalespersonId { get; set; }
        public string TaxId { get; set; }
        public string TaxFormat { get; set; }
        public string Status { get; set; }
        public string SIndicator { get; set; }
        public string TEFRA { get; set; }
        public string Cnotice { get; set; }
        public string DocumentStatus { get; set; }
        public string PayeeType { get; set; }
        public string PayeeStatus { get; set; }
        public string TreatyType { get; set; }
        public string TreatyCountry { get; set; }
        public Nullable<int> TINStatus { get; set; }
        public Nullable<int> CTIAccountNo { get; set; }
        public string DocumentStatusCode { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string AccountType { get; set; }
        public bool IsChangeNotified { get; set; }
        public Nullable<long> AccountNo { get; set; }
        public Nullable<System.DateTime> TEFRADate { get; set; }
        public Nullable<bool> SCorpIndicator { get; set; }
        public string PrimaryBusinessUnit { get; set; }
        public string SecondaryBusinessUnit { get; set; }
        public Nullable<bool> TaxAttributesOverridden { get; set; }
        public string Giin { get; set; }
        public string FatcaStatusCode { get; set; }
        public Nullable<bool> IsUSWA { get; set; }
        public bool PreExisting { get; set; }
        public Nullable<System.DateTime> FatcaStatusDate { get; set; }
        public byte FatcaStatusSourceId { get; set; }
        public string GIINStatus { get; set; }
        public Nullable<System.DateTime> GIINStatusDate { get; set; }
        public string DreGiin { get; set; }
        public Nullable<int> CTIOffshoreAccountNo { get; set; }
    
        public virtual LegalEntity LegalEntity { get; set; }
    }
}
